### ISSUE TITLE
Can you provide the source to your data?

### ISSUE THREAD

**Issue by emanuelazcona** [ykzeng/covid-19#1]
I cannot find land area data on the Census' site that you're using.

**Comment by ykzeng** [comment]
just updated the readme for this repo including data sources:

[https://github.com/ykzeng/covid-19](https://github.com/ykzeng/covid-19)

the data is very old, only found on archived websites, but it is in use by Wikipedia so I would imagine this would be the best data we can get as of now.

**Comment by emanuelazcona** [comment]
Thanks! This was much clearer. Appreciate it!

I too, think this is a very important feature to use in any kind of estimation model. If not this, population  per square mile.
